In [1]:
import os
import sys
import pandas as pd
import numpy as np
from collections import Counter
from sklearn.preprocessing import StandardScaler
import warnings

warnings.filterwarnings('ignore')

dir = "/Users/julianguyen/Documents/BCaATAC"
os.chdir(dir)
sys.path.insert(0, dir)
from utils.gene_surrogate.helpers import *

np.random.seed(101)

### Load in and format matrices

In [2]:
# load in meta
meta = pd.read_csv("data/rawdata/tcga/TCGA_sourcefiles.csv")

# load in ARCHE scores
arche_scores = pd.read_csv("data/procdata/NMF/ATAC_heatmap_rank6.png.order.matrix", sep='\t')
arche_scores.index = [f"ARCHE{i}" for i in range(1, 7)]

# match sample IDs
lookup = dict(zip(meta['ATAC.Seq.File.Name'], meta['Sample.Name']))
arche_scores.columns = [lookup.get(col.lstrip('X'), None) for col in arche_scores.columns]

# remove duplicate ATAC-seq
dupe = arche_scores.columns[arche_scores.columns.duplicated()]
arche_scores = arche_scores.drop(columns=dupe)

# load in rna
full_cohort = pd.read_csv("data/rawdata/tcga/Human__TCGA_BRCA__UNC__RNAseq__HiSeq_RNA__01_28_2016__BI__Gene__Firehose_RSEM_log2.cct", sep='\t', index_col=0)

# keep genes shared with metabric so models can be applied there
metabric_genes = pd.read_csv("data/procdata/metabric/METABRIC_BRCA_Illumina_HT12v3_microarray_log2.cct", sep='\t', usecols=[0]).iloc[:, 0]
full_cohort = full_cohort.loc[full_cohort.index.isin(metabric_genes)]

# z-score genes across the full tcga cohort
full_cohort = zscore_genes(full_cohort.T)

# match samples
rna = full_cohort.loc[full_cohort.index.isin(arche_scores.columns)]
full_cohort = full_cohort.drop(index=arche_scores.columns)

# transpose matrices
arche_scores = arche_scores.T
rna = rna.reindex(arche_scores.index)

In [3]:
arche_scores.head()

              ARCHE1  ARCHE2  ARCHE3  ARCHE4  ARCHE5  ARCHE6
TCGA.A2.A0YT    5.32    0.00     0.0     0.0     0.0     0.0
TCGA.AO.A0J5    5.16    0.02     0.0     0.0     0.0     0.0
TCGA.A2.A0YK    4.90    0.71     0.0     0.0     0.0     0.0
TCGA.BH.A0BA    4.81    0.00     0.0     0.0     0.0     0.0
TCGA.A2.A0ES    4.64    0.00     0.0     0.0     0.0     0.0

In [4]:
rna.head()

attrib_name,A1BG,A1CF,A2ML1,A2M,A4GALT,A4GNT,AAA1,AAAS,AACS,AADACL2,...,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3,psiTPTE22
TCGA.A2.A0YT,0.115952,-0.389828,0.749542,0.387211,-0.037229,-0.979741,-0.219898,-0.440024,-0.343699,-0.255508,...,0.888054,0.760496,0.162762,1.070415,0.928087,1.191117,-1.104068,0.918738,0.174339,1.124451
TCGA.AO.A0J5,-0.011511,-0.389828,-0.830734,0.389305,0.161180,0.673321,-0.219898,-0.262832,-0.135421,-0.255508,...,0.139159,0.854740,0.041757,0.468208,-1.189083,0.787553,-0.008818,0.723903,0.553953,0.098457
TCGA.A2.A0YK,-0.277768,-0.389828,0.433084,1.378348,0.008408,0.633860,-0.219898,-0.991005,-0.534960,2.467315,...,-1.101152,1.037807,0.173198,1.035613,-0.286338,0.790606,0.439297,1.394246,0.639709,0.735217
TCGA.BH.A0BA,-0.139919,1.045747,0.141623,0.325290,-0.571753,0.167804,-0.219898,0.024557,4.090529,-0.255508,...,0.290968,1.057594,0.475709,0.173368,0.292230,0.274083,-0.521989,0.506587,0.019815,0.417101
TCGA.A2.A0ES,-0.082238,-0.389828,-0.351496,1.602899,0.603988,1.328146,-0.219898,-0.423159,-0.556495,-0.255508,...,-1.741657,0.801535,0.436221,0.817337,-0.206372,0.642538,0.736328,0.652202,0.358756,0.611694

### Featre selection

In [5]:
arche1 = important_features(rna, arche_scores["ARCHE1"], thres = 0.35)
arche1 = corr_features(arche1, 0.8)

Selected threshold: 0.35
Num features with positive correlation > threshold: 192
Num features with negative correlation > threshold: 58
Total number of features: 250

Num correlated features: 44
Original number of feaures: 250
Number of features remaining: 206

In [6]:
arche2 = important_features(rna, arche_scores["ARCHE2"], thres = 0.6)
arche2 = corr_features(arche2, 0.8)

Selected threshold: 0.6
Num features with positive correlation > threshold: 162
Num features with negative correlation > threshold: 118
Total number of features: 280

Num correlated features: 38
Original number of feaures: 280
Number of features remaining: 242

In [7]:
arche3 = important_features(rna, arche_scores["ARCHE3"], thres = 0.4)
arche3 = corr_features(arche3, 0.8)

Selected threshold: 0.4
Num features with positive correlation > threshold: 172
Num features with negative correlation > threshold: 58
Total number of features: 230

Num correlated features: 19
Original number of feaures: 230
Number of features remaining: 211

In [8]:
arche4 = important_features(rna, arche_scores["ARCHE4"], thres = 0.4)
arche4 = corr_features(arche4, 0.8)

Selected threshold: 0.4
Num features with positive correlation > threshold: 138
Num features with negative correlation > threshold: 140
Total number of features: 278

Num correlated features: 18
Original number of feaures: 278
Number of features remaining: 260

In [9]:
arche5 = important_features(rna, arche_scores["ARCHE5"], thres = 0.4)
arche5 = corr_features(arche5, 0.8)

Selected threshold: 0.4
Num features with positive correlation > threshold: 468
Num features with negative correlation > threshold: 64
Total number of features: 532

Num correlated features: 231
Original number of feaures: 532
Number of features remaining: 301

In [10]:
arche6 = important_features(rna, arche_scores["ARCHE6"], thres = 0.45)
arche6 = corr_features(arche6, 0.8)

Selected threshold: 0.45
Num features with positive correlation > threshold: 161
Num features with negative correlation > threshold: 39
Total number of features: 200

Num correlated features: 11
Original number of feaures: 200
Number of features remaining: 189

### Elastic Net Models

In [11]:
run_elastic_net(arche1, arche_scores["ARCHE1"], "1-Signatures/geneSurrogates/arche1_", full_cohort)
run_elastic_net(arche2, arche_scores["ARCHE2"], "1-Signatures/geneSurrogates/arche2_", full_cohort)
run_elastic_net(arche3, arche_scores["ARCHE3"], "1-Signatures/geneSurrogates/arche3_", full_cohort)
run_elastic_net(arche4, arche_scores["ARCHE4"], "1-Signatures/geneSurrogates/arche4_", full_cohort)
run_elastic_net(arche5, arche_scores["ARCHE5"], "1-Signatures/geneSurrogates/arche5_", full_cohort)
run_elastic_net(arche6, arche_scores["ARCHE6"], "1-Signatures/geneSurrogates/arche6_", full_cohort)